#!/usr/bin/env bash

ROOT=$HOME/.config/bspwm

test -f $ROOT/autostart.sh && bash $ROOT/autostart.sh

connected_monitors=$(xrandr | grep -w 'connected' | cut -d ' ' -f 2 | wc -l)

if [[ $connected_monitors > 1 ]]; then
  monitor="HDMI-1"
else
  monitor="LVDS-1"
fi

bspc monitor $monitor -d I II III IV V VI VII VIII IX

if [[ $connected_monitors > 1 ]]; then
  bspc monitor LVDS-1 -d X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Onedark
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#528bff"
# Dracula
# bspc config normal_border_color "#282a36"
# bspc config focused_border_color "#bd93f9"
# Doom one
# bspc config normal_border_color "#282a36"
# bspc config focused_border_color "#51afef"
# Ayu Mirage
# bspc config normal_border_color "#282a36"
# bspc config focused_border_color "#60b8d6"
# Horizon Dark
# bspc config normal_border_color "#282a36"
# bspc config focused_border_color "#16bbd9"
# Moonlight
# bspc config normal_border_color "#212337"
# bspc config focused_border_color "#c099ff"
# CodeDark
# bspc config normal_border_color "#212337"
# bspc config focused_border_color "#569cd6"
# Tokyonight
# bspc config normal_border_color "#212337"
# bspc config focused_border_color "#7aa2f7"
# Tokyonight
# bspc config normal_border_color "#24283b"
# bspc config focused_border_color "#7aa2f7"
# Calvera Dark
# bspc config normal_border_color "#212337"
# bspc config focused_border_color "#7878E7"

test -f $ROOT/polybar-init.sh && bash $ROOT/polybar-init.sh
