#!/usr/bin/env bash

ROOT=$HOME/.config/bspwm

test -f $ROOT/autostart.sh && bash $ROOT/autostart.sh

connected_monitors=$(xrandr | grep -w 'connected' | cut -d ' ' -f 2 | wc -l)

if [[ $connected_monitors > 1 ]]; then
  monitor="HDMI-1"
else
  monitor="LVDS-1"
fi

bspc monitor $monitor -d I II III IV V VI VII VIII IX

if [[ $connected_monitors > 1 ]]; then
  bspc monitor LVDS-1 -d X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color "#282c34"
bspc config focused_border_color "#528bff"

test -f $ROOT/polybar-init.sh && bash $ROOT/polybar-init.sh
