vim.cmd [[ let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0 ]]
require('variables')
require('plugins')
-- ;;;
-- require('uwu_config')
-- require('gotham_config')
-- require('tokyonight_config')
-- require('moonlight_config')
-- require('code_config')
-- require('onedark_config')
-- require('nightfox_config')
require('onedarker_config')
-- require('calvera_config')
-- require('onedark_config')
-- require('onedark_vim_config')
-- require('material_config')
-- require('horizon_config')
-- require('gruvbox_material_config')
-- require('edge_config')
-- require('dracula_config')
-- require('doom_one_config')
-- require('ayu_config')
-- require('solarized_config')
-- ;;;
-- require('lualine_config')
-- require('evil_lualine')
-- ;;;
require('nvim_tree')
-- require('bufferline_config')
-- require('auto_pairs_config')
require('treesitter_config')
require('colorizer_config')
require('fterm_config')
require('comment_config')
require('neoscroll_config')
require('eob')
require('neovide_config')
require('toggleterm_config')
-- vim.cmd [[ source $HOME/.config/nvim/coc.vim ]]
require('symbols_outline_config')
-- ;;
require('keymaps')
