require('variables')
require('keymaps')
require('plugins')
-- require('tokyonight_config')
require('moonlight_config')
-- require('code_config')
-- require('onedark_config')
-- require('nightfox_config')
-- require('calvera_config')
-- require('onedark_config')
-- require('material_config')
-- require('gruvbox_config')
-- require('horizon_config')
-- require('dracula_config')
-- ;;;
-- require('lualine_config')
require('evil_lualine')
require('nvim_tree')
require('bufferline_config')
require('auto_pairs_config')
require('treesitter_config')
require('colorizer_config')
require('fterm_config')
require('comment_config')
require('neoscroll_config')
require('eob')
vim.cmd [[ source $HOME/.config/nvim/coc.vim ]]
